//
//  OwnerReceivedVehicleRequest.swift
//  FindDriver
//
//  Created by Miad Azarmehr on 2019-04-07.
//  Copyright © 2019 Miad Azarmehr. All rights reserved.
//

import UIKit
import Firebase

class OwnerReceivedVehicleRequest: UITableViewController {
    
    
    @IBOutlet var driverNameLabel: UILabel!
    @IBOutlet var driverPhoneLabel: UILabel!
    
    
    var ref: DatabaseReference?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ref = Database.database().reference()
        
        driverNameLabel.text = vehicleArray[vehicleIndex].driverName
        driverPhoneLabel.text = vehicleArray[vehicleIndex].driverPhone
        
        
    }
    
    @IBAction func acceptRequest(_ sender: UIButton) {
        
        let vehicleAutoGeneratedKey = vehicleArray[vehicleIndex].vehicleAutoGenerateKey
        print( "documentAutoGeneratedKey = retreiveVehicleDetails.vehicleAutoGenerateKey \(vehicleAutoGeneratedKey)")
        
        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
        
        let dictionaryValue = ["requestAccepted": true, "availability": false]
        
        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            
            print("Request accepted! \(vehicleAutoGeneratedKey)")
            
        })
        dismiss(animated: true, completion: nil)
    }
    
    
    
    @IBAction func denyRequest(_ sender: UIButton) {
        
        let vehicleAutoGeneratedKey = vehicleArray[vehicleIndex].vehicleAutoGenerateKey
        print( "documentAutoGeneratedKey = retreiveVehicleDetails.vehicleAutoGenerateKey \(vehicleAutoGeneratedKey)")
        
        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
        
        let dictionaryValue = ["requestAccepted": false]
        
        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            
            print("Request accepted! \(vehicleAutoGeneratedKey)")
            
        })
        dismiss(animated: true, completion: nil)
        
    }
    
}
