//
//  OwnerReceivedVehicleRequest.swift
//  FindDriver
//
//  Created by Miad Azarmehr on 2019-04-07.
//  Copyright © 2019 Miad Azarmehr. All rights reserved.
//

import UIKit
import Firebase

class OwnerReceivedVehicleRequest: UITableViewController {
    
    @IBOutlet var driverNameLabel: UILabel!
    @IBOutlet var driverPhoneLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ref = Database.database().reference()
        
        driverNameLabel.text = requestedVehiclesArray[requestedIndex].driverName
        driverPhoneLabel.text = requestedVehiclesArray[requestedIndex].driverPhone
    }
    
    @IBAction func acceptRequest(_ sender: UIButton) {
        
        let vehicleAutoGeneratedKey = requestedVehiclesArray[requestedIndex].vehicleAutoGeneratedKey
        print( "documentAutoGeneratedKey = retreiveVehicleDetails.vehicleAutoGenerateKey \(vehicleAutoGeneratedKey)")
        
        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
        
        let dictionaryValue = ["requestAccepted": true, "availability": false] as [String : Any]
        
        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            print("Request accepted! \(vehicleAutoGeneratedKey)")
        })
        
        let driverAutoGeneratedKey = requestedVehiclesArray[requestedIndex].driverAutoGeneratedKey
        let driverIndexPathInFirebase = ref?.child("profiles").child(driverAutoGeneratedKey)
        
        let dictionaryValue2 = ["vehicleAutoGeneratedKey": vehicleAutoGeneratedKey, "ownerID": currentLoggedInOwner, "connectedToAnyVehicles": true] as [String : Any]
        
        driverIndexPathInFirebase?.updateChildValues(dictionaryValue2, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            print("vehicle auto generated key added to driver's profile! \(vehicleAutoGeneratedKey)")
        })
 //       dismiss(animated: true, completion: nil)
    }
    
    
    
    @IBAction func denyRequest(_ sender: UIButton) {
        
        let vehicleAutoGeneratedKey = requestedVehiclesArray[requestedIndex].vehicleAutoGeneratedKey
        print( "documentAutoGeneratedKey = retreiveVehicleDetails.vehicleAutoGenerateKey \(vehicleAutoGeneratedKey)")
        
        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
        
        let dictionaryValue = ["availability": true, "driverID": "", "driverName": "", "driverPhone": "", "requestAccepted": false, "vehicleRequested": false, "driverAutoGeneratedKey": ""] as [String : Any]
        
        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            print("Request accepted! \(vehicleAutoGeneratedKey)")
        })
 //       dismiss(animated: true, completion: nil)
        
        
        let driverAutoGeneratedKey = requestedVehiclesArray[requestedIndex].driverAutoGeneratedKey
        let driverIndexPathInFirebase = ref?.child("profiles").child(driverAutoGeneratedKey)
        
        let dictionaryValue2 = ["vehicleAutoGeneratedKey": "", "ownerID": "", "connectedToAnyVehicles": false] as [String : Any]
        
        driverIndexPathInFirebase?.updateChildValues(dictionaryValue2, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            print("vehicle auto generated key added to driver's profile! \(vehicleAutoGeneratedKey)")
        })
    }
}
