//
//  EdditOwnerVehicleTVC.swift
//  FindDriver
//
//  Created by mobileapps on 2019-04-05.
//  Copyright © 2019 Miad Azarmehr. All rights reserved.
//

import UIKit
import Firebase

class EditOwnerVehicleTVC: UITableViewController {
    
    
    @IBOutlet weak var typeTextfield: UITextField!
    @IBOutlet weak var brandTextfield: UITextField!
    @IBOutlet weak var modelTextfield: UITextField!
    @IBOutlet weak var yearTextfield: UITextField!
    @IBOutlet weak var weeklyTextfield: UITextField!
    @IBOutlet var availableToogleSwitch: UISwitch!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ref = Database.database().reference()
        
        typeTextfield.text = vehicleArray[vehicleIndex].type
        brandTextfield.text = vehicleArray[vehicleIndex].brand
        modelTextfield.text = vehicleArray[vehicleIndex].model
        yearTextfield.text = vehicleArray[vehicleIndex].year
        weeklyTextfield.text = vehicleArray[vehicleIndex].weeklyRent
        
    }
    
    @IBAction func saveVehicleChangesButton(_ sender: UIBarButtonItem) {
        
        let toogleNewStatus = availableToogleSwitch.isOn
        let vehicleAutoGeneratedKey = vehicleArray[vehicleIndex].vehicleAutoGeneratedKey
        print( "documentAutoGeneratedKey = retreiveVehicleDetails.vehicleAutoGenerateKey \(vehicleAutoGeneratedKey)")
        
        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
        
        let dictionaryValue = ["type": typeTextfield.text!, "brand": brandTextfield.text!, "model": modelTextfield.text!, "year": yearTextfield.text!, "weeklyRent": weeklyTextfield.text!, "availability": toogleNewStatus] as [String : Any]
        
        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            
            print("Vehicle updated successfuly \(vehicleAutoGeneratedKey)")
            
        })
        dismiss(animated: true, completion: nil) 
    }
}


