//
//  ShowPaymentDetailsTVC.swift
//  FindDriver
//
//  Created by Miad Azarmehr on 2019-04-14.
//  Copyright © 2019 Miad Azarmehr. All rights reserved.
//

import UIKit
import Firebase

class ShowPaymentDetailsTVC: UITableViewController {
    
    
    @IBOutlet var paymentDetailLabel: UILabel!
    @IBOutlet var messageTextfield: UITextView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ref = Database.database().reference()
        
        paymentDetailLabel.text = "\(paymentArray[paymentIndex].startDate) TO: \(paymentArray[paymentIndex].endDate) \(paymentArray[paymentIndex].amount) sent."
    }
    
    @IBAction func acceptPaymentButton(_ sender: UIButton) {
        
        let paymentAutoGeneratedKey = paymentArray[paymentIndex].paymentAutoGeneratedKey
        let paymentIndexPathInFirebase = ref?.child("payments").child(paymentAutoGeneratedKey)
        let paymentDictionary = ["ownerMessage" : self.messageTextfield.text, "paymentConfirmed": true] as [String : Any]
        paymentIndexPathInFirebase?.updateChildValues(paymentDictionary, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            print("Payment accepted!")
        })
    }
    
    
    @IBAction func rejectPaymentButton(_ sender: UIButton) {
        let paymentAutoGeneratedKey = paymentArray[paymentIndex].paymentAutoGeneratedKey
        let paymentIndexPathInFirebase = ref?.child("payments").child(paymentAutoGeneratedKey)
        let paymentDictionary = ["ownerMessage" : self.messageTextfield.text, "paymentConfirmed": false] as [String : Any]
        paymentIndexPathInFirebase?.updateChildValues(paymentDictionary, withCompletionBlock: { (error, ref) in
            if error != nil {
                print(error!)
            }
            print("Payment refused!")
        })
        
    }
    
    
    
    //
    //    @IBAction func sendConnectionRequestToOwner(_ sender: UIBarButtonItem) {
    //
    //        requestStatus.text = "Request pending!"
    //
    //        let vehicleAutoGeneratedKey = vehicleArray[vehicleIndex].vehicleAutoGeneratedKey
    //
    //        print( "documentAutoGeneratedKey = retreiveVehicleDetails.vehicleAutoGenerateKey \(vehicleGeneratedKey)")
    //
    //        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
    //
    //        let dictionaryValue = ["vehicleRequested": true, "driverID": driverInstance.driverID, "driverPhone": driverInstance.phone, "driverName": "\(driverInstance.firstName)  \(driverInstance.lastName)", "driverAutoGeneratedKey": driverInstance.driverAutoGenerateKey] as [String : Any]
    //
    //        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
    //            if error != nil {
    //                print(error!)
    //            }
    //            print("Rent Rquest Sent To Owner's Vehicle \(vehicleGeneratedKey)")
    //            // self.dismiss(animated: false, completion: nil)
    //        })
    //    }
    //
    //
    //    @IBAction func disconnect(_ sender: UIButton) {
    //
    //        let vehicleAutoGeneratedKey = vehicleArray[vehicleIndex].vehicleAutoGeneratedKey
    //
    //        let vehicleIndexPathInFirebase = ref?.child("vehicles").child(vehicleAutoGeneratedKey)
    //
    //        let dictionaryValue = ["vehicleRequested": false, "driverID": "", "driverPhone": "", "driverName": "" ,"requestAccepted": false, "availability": true, "driverAutoGeneratedKey": "", "connectedToDriver": ""] as [String : Any]
    //
    //        vehicleIndexPathInFirebase?.updateChildValues(dictionaryValue, withCompletionBlock: { (error, ref) in
    //            if error != nil {
    //                print(error!)
    //            }
    //            print("Rent Rquest Sent To Owner's Vehicle \(vehicleAutoGeneratedKey)")
    //        })
    //
    //
    //        let driverAutoGeneratedKey = driverInstance.driverAutoGenerateKey
    //        let driverIndexPathInFirebase = ref?.child("profiles").child(driverAutoGeneratedKey)
    //
    //        let dictionaryValue2 = ["vehicleAutoGeneratedKey": "", "connectedToAnyVehicles": false, "ownerID": ""] as [String : Any]
    //
    //        driverIndexPathInFirebase?.updateChildValues(dictionaryValue2, withCompletionBlock: { (error, ref) in
    //            if error != nil {
    //                print(error!)
    //            }
    //            print("vehicle auto generated key removed from driver's profile! \(vehicleAutoGeneratedKey)")
    //        })
    //        //        dismiss(animated: true, completion: nil)
    //    }
}
