//
//  DriverFindVehicleTableViewController.swift
//  FindDriver
//
//  Created by Miad Azarmehr on 2019-04-02.
//  Copyright © 2019 Miad Azarmehr. All rights reserved.
//

import UIKit
import Firebase

class DriverFindAvailableVehicleTableViewController: UIViewController, UITableViewDataSource, UITableViewDelegate {
    
    
    @IBOutlet weak var tableView: UITableView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.dataSource = self
        tableView.delegate = self
        
        tableView.register(UINib(nibName: "MessageCell", bundle: nil) , forCellReuseIdentifier: "customMessageCell")
        
        configureTableView()
    }
    
    func configureTableView() {
        
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 120.0
    }
    
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        print("HERE IN CELL FOR ROW AT")
        let cell = tableView.dequeueReusableCell(withIdentifier: "customMessageCell", for: indexPath) as! CustomMessageCell
        
         cell.vehicleDetailLabel.text = "\(vehicleArray[indexPath.row].type) \(vehicleArray[indexPath.row].brand) \(vehicleArray[indexPath.row].model) \(vehicleArray[indexPath.row].year) $\(vehicleArray[indexPath.row].weeklyRent)  \(vehicleArray[indexPath.row].vehicleAutoGeneratedKey)"
        
        return cell
    }
    
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        print ("vehiclecount -------> \(vehicleArray.count)")
        return vehicleArray.count
    }
    
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        print("HERE IN DID SELECT ROW AT")
        vehicleIndex = indexPath.row
        performSegue(withIdentifier: "sendVehicleRequestCell", sender: self)
    }
    
    
    @IBAction func unwindToFindVehicleForRent(_ unwindSegue: UIStoryboardSegue) {
        
    }
}
