//
//  MakePaymentTVC.swift
//  FindDriver
//
//  Created by Miad Azarmehr on 2019-04-07.
//  Copyright © 2019 Miad Azarmehr. All rights reserved.
//

import UIKit
import Firebase

class MakePaymentTVC: UITableViewController {
    
    
    @IBOutlet var startDatePicker: UIDatePicker!
    @IBOutlet var endDatePicker: UIDatePicker!
    @IBOutlet var amountTestfield: UITextField!
    
    var ref: DatabaseReference?
    var startDate = ""
    var endDate = ""
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        ref = Database.database().reference()
    }
    
    
    @IBAction func startDateUIDate(_ sender: UIDatePicker) {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MMM/yyyy"
        startDate = formatter.string(from: startDatePicker.date)
    }
    
    
    @IBAction func endDateUIDate(_ sender: UIDatePicker){
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MMM/yyyy"
        endDate = formatter.string(from: endDatePicker.date)
    }
    
    
    @IBAction func sendPaymentButton(_ sender: UIBarButtonItem) {

        let amountToPay = amountTestfield.text ?? "0"
        
        let vehicleDB = Database.database().reference().child("payments").childByAutoId()
        
        let vehicleDictionary = [ "startDate": startDate, "endDate": endDate, "amount": amountToPay, "driverID": driverInstance.driverID, "paymentConfirmed": false, "driverAutoGenerateKey": driverInstance.driverAutoGenerateKey, "ownerID": driverInstance.ownerID, "vehicleAutoGeneratedKey": driverInstance.vehicleAutoGeneratedKey, "driverPhone": driverInstance.phone] as [String : Any]
        
        vehicleDB.setValue(vehicleDictionary) {
            (error, reference) in
            if error != nil {
                print(error!)
            } else {
                print("Payment sent successfuly")
            }
        }
//        dismiss(animated: false, completion: nil)
    }
}
